version: 2

references:
  base_docker: &base_docker
    working_directory: ~/repo
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps-node-browsers
    environment:
      JVM_OPTS: -Xmx3200m

jobs:
  test_clj:
    <<: *base_docker
    steps:
      - checkout
      - restore_cache:
          key: periscope-{{ checksum "deps.edn" }}

      - save_cache:
          paths:
            - ~/.m2

          key: periscope-{{ checksum "deps.edn" }}

      - run: ./bin/kaocha

  test_cljs_node:
    <<: *base_docker
    steps:
      - checkout
      - restore_cache:
          key: periscope-{{ checksum "deps.edn" }}

      - run: sudo npm install karma-cli@2.0.0 -g
      - run: npm install karma@5.2.3 --save-dev
      - run: npm install karma-chrome-launcher@3.1.0
      - run: npm install karma-cljs-test@0.1.0
      - run: clojure -Sverbose -M:test-chrome

workflows:
  version: 2
  build:
    jobs:
      - test_clj
      - test_cljs_node
