version: 2

references:
  base_docker: &base_docker
    working_directory: ~/repo
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps-node-browsers
    environment:
      JVM_OPTS: -Xmx3200m

jobs:
  test_clj:
    <<: *base_docker
    steps:
      - checkout
      - restore_cache:
          key: periscope-{{ checksum "deps.edn" }}

      - save_cache:
          paths:
            - ~/.m2

          key: periscope-{{ checksum "deps.edn" }}

      - run: ./bin/kaocha

workflows:
  version: 2
  build:
    jobs:
      - test_clj
